
wizardalley_user_login:
    path:     /login
    defaults: { _controller: WizardalleyUserBundle:Security:login }

wizardalley_user_profile_edit_picture:
    path:   /user/editPictureProfile
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editProfilePicture }
    
wizardalley_user_couverture_edit_picture:
    path:   /user/editPictureCouverture
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editCouverturePicture }

wizardalley_user_wall:
    path:   /wall/{id}
    defaults: { _controller: WizardalleyUserBundle:Default:userWall, id : 1 }

wizardalley_user_wall_publication:
    path:   /wall/publication/{page}
    defaults: { _controller: WizardalleyUserBundle:Default:displayPublicationUser, page: 1 }


login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

wizard_add_as_a_friend:
    path:   /user/addAsAFriend/{id_user}
    defaults: { _controller: WizardalleyUserBundle:Default:addAsAFriend }


wizard_get_friends_json:
    path:   /user/getFriendsJson/{page}
    defaults: { _controller: WizardalleyUserBundle:Default:friendList, page: 1 }

wizard_get_friends_view:
    path:   /user/getFriendsView
    defaults: { _controller: WizardalleyUserBundle:Default:displayFriendList }


wizard_get_publication_view:
    path:   /user/getPublication/{page}
    defaults: { _controller: WizardalleyUserBundle:Default:displayPublicationPage, page: 1 }

wizard_search_user_json:
    path:   /search/user/{search}
    defaults: { _controller: WizardalleyUserBundle:Default:searchUserJson, search: -1}