
wizardalley_user_login:
    path:     /login
    defaults: { _controller: WizardalleyUserBundle:Security:login }

wizardalley_user_profile_edit_picture:
    path:   /user/editPictureProfile
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editProfilePicture }
    
wizardalley_user_couverture_edit_picture:
    path:   /user/editPictureCouverture
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editCouverturePicture }


login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

user_notification:
    resource: "@WizardalleyUserBundle/Controller/NotificationController.php"
    type:     annotation
    prefix:   /

user_default:
    resource: "@WizardalleyUserBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

user_message:
    resource: "@WizardalleyUserBundle/Controller/MessageController.php"
    type:     annotation
    prefix:   /


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile