
wizardalley_user_login:
    path:     /login
    defaults: { _controller: WizardalleyUserBundle:Security:login }

wizardalley_user_profile_edit_picture:
    path:   /user/editPictureProfile
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editProfilePicture }
    
wizardalley_user_couverture_edit_picture:
    path:   /user/editPictureCouverture
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editCouverturePicture }

wizardalley_user_wall:
    path:   /user/wall/display/{id}
    defaults: { _controller: WizardalleyUserBundle:Default:userWall, id : 1 }


wizardalley_user_wall_publication:
    path:   /user/wall/publication/{page}
    defaults: { _controller: WizardalleyUserBundle:Default:displayPublicationUser, page: 1 }
    options:
        expose: true

wizardalley_user_wall_publication_json:
    path:   /user/wall/publicationJson/{id}
    defaults: { _controller: WizardalleyUserBundle:Default:displayPublicationWall, id: null }
    options:
        expose: true

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

wizard_add_as_a_friend:
    path:   /user/addAsAFriend/{id_user}
    defaults: { _controller: WizardalleyUserBundle:Default:addAsAFriend }

wizard_friend_list:
    path:   /user/getFriendLIst
    defaults: { _controller: WizardalleyUserBundle:Default:getFriendList }
    options:
        expose: true

wizard_user_connected:
    path:   /user/getUserConnected
    defaults: { _controller: WizardalleyUserBundle:Default:getUserConnected }
    options:
        expose: true


wizard_get_friends_json:
    path:   /user/getFriendsJson/{page}
    defaults: { _controller: WizardalleyUserBundle:Default:friendList, page: 1 }
    options:
        expose: true


wizard_get_friends_view:
    path:   /user/getFriendsView
    defaults: { _controller: WizardalleyUserBundle:Default:displayFriendList }


wizard_get_publication_view:
    path:   /user/getPublication/{page}
    defaults: { _controller: WizardalleyUserBundle:Default:displayPublicationPage, page: 1 }
    options:
        expose: true

wizard_search_user_json:
    path:   /search/user/{search}
    defaults: { _controller: WizardalleyUserBundle:Default:searchUserJson, search: -1}



user_notification:
    resource: "@WizardalleyUserBundle/Controller/NotificationController.php"
    type:     annotation
    prefix:   /

fos_user_profile_show:
    path: /profile/
    defaults: { _controller: FOSUserBundle:Profile:show }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile