
wizardalley_user_login:
    path:     /login
    defaults: { _controller: WizardalleyUserBundle:Security:login }

wizardalley_user_profile_edit_picture:
    path:   /user/editPictureProfile
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editProfilePicture }
    
wizardalley_user_couverture_edit_picture:
    path:   /user/editPictureCouverture
    defaults: { _controller: WizardalleyUserBundle:ProfilePicture:editCouverturePicture }

wizardalley_user_wall:
    path:   /wall/{id}
    defaults: { _controller: WizardalleyUserBundle:Default:userWall }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

wizard_add_as_a_friend:
    path:   /user/addAsAFriend/{id_user}
    defaults: { _controller: WizardalleyUserBundle:Default:addAsAFriend }


wizard_get_friends_json:
    path:   /user/getFriendsJson
    defaults: { _controller: WizardalleyUserBundle:Default:friendList }

wizard_get_friends_view:
    path:   /user/getFriendsView
    defaults: { _controller: WizardalleyUserBundle:Default:displayFriendList }


