services:
    wizard_alley.registration.form.type:
        class: Wizardalley\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wizard_user_registation }
    wizard_alley.profile.form.type:
        class: Wizardalley\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wizard_user_profile_edit }
    wizard.user.twig.notification:
        class: Wizardalley\UserBundle\Twig\NotificationExtension
        arguments: ['@security.token_storage', '@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }
    wizard.user.twig.message:
        class: Wizardalley\UserBundle\Twig\MessageExtension
        arguments: ['@security.token_storage', '@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }

    fos_user.registration.form.handler.default:
        class: Wizardalley\UserBundle\Form\Handler\RegistrationFormHandler
        scope: request
        public: false
        arguments: ['@fos_user.registration.form', '@request', '@fos_user.user_manager', '@fos_user.mailer', '@fos_user.util.token_generator', '%kernel.root_dir%']

