services:
    wizard_alley.registration.form.type:
        class: Wizardalley\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wizard_user_registation }