wizardalley_publication_publication:
    resource: "@WizardalleyPublicationBundle/Controller/PublicationController.php"
    type:     annotation
    prefix:   /

wizardalley_gestion_page:
    resource: "@WizardalleyPublicationBundle/Controller/GestionPageController.php"
    type:     annotation
    prefix:   /

wizardalley_publication_small_publication:
    resource: "@WizardalleyPublicationBundle/Controller/SmallPublicationController.php"
    type:     annotation
    prefix:   /

wizardalley_page:
    resource: "@WizardalleyPublicationBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /
