wizardalley_publication_publication:
    resource: "@WizardalleyPublicationBundle/Controller/PublicationController.php"
    type:     annotation
    prefix:   /

wizardalley_publication_small_publication:
    resource: "@WizardalleyPublicationBundle/Resources/config/routing/small_publication.yml"
    prefix:   /

wizardalley_page:
    resource: "@WizardalleyPublicationBundle/Resources/config/routing/page.yml"
    prefix:   /

wizardalley_gestion_page:
    resource: "@WizardalleyPublicationBundle/Resources/config/routing/gestion_page.yml"
    prefix:   /