
services:
    wizard.publication.twig.html_strip_extension:
        class: Wizardalley\PublicationBundle\Twig\HTMLLimitStripExtension
        tags:
            - { name: twig.extension }
    wizard.publication.twig.user_like:
        class: Wizardalley\PublicationBundle\Twig\LikePublicationExtension
        arguments: ['@security.token_storage', '@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }
    wizard.publication.twig.blame:
        class: Wizardalley\PublicationBundle\Twig\BlameExtension
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: twig.extension }
    wizard.helper.publication.notification:
        class: Wizardalley\PublicationBundle\Helper\PublicationNotificationHelper
        arguments: ['@doctrine.orm.default_entity_manager']

