

vich_uploader:
    db_driver: orm
    mappings:
        map_images:
            uri_prefix:         %app.path.map_images%
            upload_destination: %kernel.root_dir%/../web/uploads/map
        category_images:
            uri_prefix:         %app.path.category_images%
            upload_destination: %kernel.root_dir%/../web/uploads/category
        page_profile_images:
            uri_prefix:         %app.path.page_profile_images%
            upload_destination: %kernel.root_dir%/../web/uploads/page/profile
        page_cover_images:
            uri_prefix:         %app.path.page_cover_images%
            upload_destination: %kernel.root_dir%/../web/uploads/page/cover
        profile_images:
            uri_prefix:         %app.path.profile_images%
            upload_destination: %kernel.root_dir%/../web/uploads/profile
        publication_images:
            uri_prefix:         %app.path.publication_images%
            upload_destination: %kernel.root_dir%/../web/uploads/publications
        page_category_images:
            uri_prefix:         %app.path.page_category_images%
            upload_destination: %kernel.root_dir%/../web/uploads/page/category

easy_admin:
    site_name: Wizard's alley
    entities:
        Page:
            class: Wizardalley\CoreBundle\Entity\Page
            list:
                fields:
                    - id
                    - name
                    - category
                    - { property: 'created_at', type: 'datetime' }
            form:
                fields:
                    - name
                    - description
                    - { property: 'fileProfile', type: 'vich_image'}
                    - { property: 'fileCouverture', type: 'vich_image'}
                    - { property: 'url_facebook', type: 'text' }
                    - category
        InformationBillet:
            class: Wizardalley\CoreBundle\Entity\InformationBillet
            form:
                fields:
                    - name
                    - content
                    - datePublicationBillet
        MapObject:
            class: Wizardalley\CoreBundle\Entity\MapObject
            list:
                fields:
                    - id
                    - title
                    - description
                    - 'links'
            form:
                fields:
                    - title
                    - description
                    - { property: 'fileLogo', type: 'vich_image'}
                    - { property: 'links', type: 'collection', type_options: { entry_type: 'Wizardalley\AdminBundle\Form\MapLinkType', by_reference: false } }

        PageCategory:
            class: Wizardalley\CoreBundle\Entity\PageCategory
            list:
                fields:
                    - id
                    - name
                    - description
            form:
                fields:
                    - name
                    - description
                    - { property: 'fileLogo', type: 'vich_image'}
        PageFavorite:
            class: Wizardalley\CoreBundle\Entity\PageFavorite
        Publication:
            class: Wizardalley\CoreBundle\Entity\Publication
            list:
                fields:
                    - id
                    - title
                    - user
                    - created_at
            form:
                fields:
                    - title
                    - small_content
                    - content
                    - user
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'Wizardalley\AdminBundle\Form\ImagePublicationType', by_reference: false } }

        WizardUser:
            class: Wizardalley\CoreBundle\Entity\WizardUser
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - locked
                    - { property: 'roles', type: 'entity'}
                    - firstname
                    - lastname
                    - twitter
                    - facebook