

vich_uploader:
    db_driver: orm
    mappings:
        map_images:
            uri_prefix:         %app.path.map_images%
            upload_destination: %kernel.root_dir%/../web/uploads/map
        category_images:
            uri_prefix:         %app.path.category_images%
            upload_destination: %kernel.root_dir%/../web/uploads/category
        page_profile_images:
            uri_prefix:         %app.path.page_profile_images%
            upload_destination: %kernel.root_dir%/../web/uploads/page/profile
        page_cover_images:
            uri_prefix:         %app.path.page_cover_images%
            upload_destination: %kernel.root_dir%/../web/uploads/page/cover
        profile_images:
            uri_prefix:         %app.path.profile_images%
            upload_destination: %kernel.root_dir%/../web/uploads/profile
        publication_images:
            uri_prefix:         %app.path.publication_images%
            upload_destination: %kernel.root_dir%/../web/uploads/publications
        page_category_images:
            uri_prefix:         %app.path.page_category_images%
            upload_destination: %kernel.root_dir%/../web/uploads/page/category

easy_admin:
    design:
        brand_color: '#1ABC9C'
        menu:
            - { entity: 'Page', icon: 'group' }
            - { entity: 'Publication', icon: 'sticky-note' }
            - { entity: 'InformationBillet', label: 'Billet d''information', icon: 'info' }
            - { entity: 'MapObject', label: 'Objet de carte', icon: 'map' }
            - { entity: 'PageCategory', label: 'Catégorie des pages', icon: 'tag' }
            - { entity: 'WizardUser', label: 'Administrateur', icon: 'user' }
            - { entity: 'User', label: 'Utilisateur', icon: 'user' }
            - { label: 'Statistique', route: 'wizardalley_admin_statistic_statistic' }
    site_name: Wizard's alley
    entities:
        Page:
            disabled_actions: ['new', 'delete']
            class: Wizardalley\CoreBundle\Entity\Page
            list:
                actions:
                    - { name: 'page_fav', type: 'route' , icon: 'heart', label: 'Ajouter favoris'}
                    - { name: 'page_unfav', type: 'route', icon: 'heart-o', label: 'Supprimer des favoris' }
                fields:
                    - id
                    - name
                    - category
                    - officialPage
                    - redactorPage
                    - { property: 'created_at', type: 'datetime' }
            form:
                fields:
                    - name
                    - { property: 'description', type: 'ckeditor'}
                    - officialPage
                    - redactorPage
                    - { property: 'fileProfile', type: 'vich_image'}
                    - { property: 'fileCouverture', type: 'vich_image'}
                    - { property: 'url_facebook', type: 'url' }
                    - category
        InformationBillet:
            disabled_actions: ['delete']
            class: Wizardalley\CoreBundle\Entity\InformationBillet
            form:
                fields:
                    - name
                    - content
                    - datePublicationBillet
        MapObject:
            disabled_actions: ['delete']
            class: Wizardalley\CoreBundle\Entity\MapObject
            list:
                fields:
                    - id
                    - title
                    - description
                    - 'links'
            form:
                fields:
                    - title
                    - description
                    - { property: 'fileLogo', type: 'vich_image'}
                    - { property: 'links', type: 'collection', type_options: { entry_type: 'Wizardalley\AdminBundle\Form\MapLinkType', by_reference: false } }

        PageCategory:
            disabled_actions: ['delete']
            class: Wizardalley\CoreBundle\Entity\PageCategory
            list:
                fields:
                    - id
                    - name
                    - description
            form:
                fields:
                    - name
                    - description
                    - { property: 'fileLogo', type: 'vich_image'}
        Publication:
            disabled_actions: ['new', 'delete']
            class: Wizardalley\CoreBundle\Entity\Publication
            list:
                actions:
                    - { name: 'publication_fav', type: 'route' , icon: 'heart', label: 'Ajouter favoris'}
                    - { name: 'publication_unfav', type: 'route', icon: 'heart-o', label: 'Supprimer des favoris' }
                fields:
                    - id
                    - title
                    - user
                    - created_at
            form:
                fields:
                    - title
                    - { property: 'small_content', type: 'ckeditor'}
                    - { property: 'content', type: 'ckeditor'}
                    - user
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'Wizardalley\AdminBundle\Form\ImagePublicationType', by_reference: false } }

        WizardUser:
            disabled_actions: ['delete']
            class: Wizardalley\CoreBundle\Entity\WizardUser
            label: 'Administrateur'
            templates:
                edit: '@WizardalleyAdmin/User/show.html.twig'
            list:
                dql_filter: "entity.roles like '%%ROLE_ADMIN%%'"
                actions:
                  - { name: 'new', label: 'Créer un adminstrateur' }
            form:
                fields:
                    - username
                    - { property: 'email', type: 'email'}
                    - enabled
                    - locked
                    - { property: 'sexe', firstnametype: 'choice', choices:['Homme','Femme'] }
                    - lastname
                    - { property: 'twitter', type: 'url'}
                    - { property: 'facebook', type: 'url'}
                    - { property: 'password', type: 'repeated'}
        User:
            disabled_actions: ['new', 'delete']
            class: Wizardalley\CoreBundle\Entity\WizardUser
            label: 'Utilisateur'
            templates:
                edit: '@WizardalleyAdmin/User/show.html.twig'
            list:
                dql_filter: "entity.roles like '%%a:0:{}%%'"
            form:
                fields:
                    - username
                    - { property: 'email', type: 'email'}
                    - enabled
                    - locked
                    - firstname
                    - { property: 'sexe', type: 'choice', type_options: {choices: {'0':'Homme', '1':'Femme'}}}
                    - lastname
                    - { property: 'twitter', type: 'url'}
                    - { property: 'facebook', type: 'url'}