wizardalley_admin:
    resource: "@WizardalleyAdminBundle/Controller/"
    type:     annotation
    prefix:   /

wizardalley_publication:
    resource: "@WizardalleyPublicationBundle/Resources/config/routing.yml"
    prefix:   /

wizardalley_default:
    resource: "@WizardalleyDefaultBundle/Resources/config/routing.yml"
    prefix:   /

wizardalley_user:
    resource: "@WizardalleyUserBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile