
wizardalley_admin:
    resource: "@WizardalleyAdminBundle/Resources/config/routing.yml"


wizardalley_publication:
    resource: "@WizardalleyPublicationBundle/Resources/config/routing.yml"
    prefix:   /

wizardalley_default:
    resource: "@WizardalleyDefaultBundle/Resources/config/routing.yml"
    prefix:   /

wizardalley_user:
    resource: "@WizardalleyUserBundle/Resources/config/routing.yml"
    prefix:   /

wizardalley_api:
    resource: "@WizardalleyWebServiceBundle/Resources/config/routing.yml"
    prefix:   /api


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"



_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /user/message

api_login_check:
    path: /api/login_check
    options:
        expose: true