
wizardalley_admin:
    resource: "@WizardalleyAdminBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@WizardalleyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /easyadmin

wizardalley_admin_statistique:
    resource: "@WizardalleyAdminBundle/Controller/StatisticController.php"
    type:     annotation
    prefix:   /easyadmin


wizardalley_publication:
    resource: "@WizardalleyPublicationBundle/Resources/config/routing.yml"
    prefix:   /

wizardalley_default:
    resource: "@WizardalleyDefaultBundle/Resources/config/routing.yml"
    prefix:   /

wizardalley_user:
    resource: "@WizardalleyUserBundle/Resources/config/routing.yml"
    prefix:   /


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /user/message

api_login_check:
    path: /api/login_check
    options:
        expose: true