# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
    encoders:
        Wizardalley\UserBundle\Entity\WizardUser: sha512

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: wizardalley_user_login
                check_path: login_check
                default_target_path:     fos_user_profile_show
            logout:
                path:       logout
                target:     wizardalley_user_login
            remember_me:
                key:        %secret%
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
