# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
    encoders:
        Wizardalley\CoreBundle\Entity\WizardUser: sha512

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/api/login
            provider:       main
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            provider:       main
            lexik_jwt: ~
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: wizardalley_user_login
                check_path: login_check
                default_target_path:     fos_user_profile_show
            logout:
                path:       logout
                target:     wizardalley_user_login
            remember_me:
                key:        %secret%


    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
