<?php

namespace Wizardalley\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformationBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationBilletRepository extends EntityRepository
{
}
