Wizardalley\CoreBundle\Entity\WizardUser:
    properties:
        fileProfile:
            - Image:
                minWidth: 99
                maxWidth: 501
                minHeight: 99
                maxHeight: 501