Wizardalley\CoreBundle\Entity\WizardUser:
    properties:
        fileProfile:
            - Image:
                minWidth: 100
                maxWidth: 500
                minHeight: 100
                maxHeight: 500