Wizardalley\CoreBundle\Entity\WizardUser:
    properties:
        fileProfile:
            - Image:
                minWidth: 200
                maxWidth: 400
                minHeight: 200
                maxHeight: 400