wizardalley_chat_homepage:
    path:     /user/chat
    defaults: { _controller: WizardalleyChatBundle:Default:index }


wizardalley_chat_user_list:
    path:     /user/chat/getUser
    defaults: { _controller: WizardalleyChatBundle:Default:getUser }

wizardalley_chat_conversation_2_user:
    path:     /user/chat/conversation2
    defaults: { _controller: WizardalleyChatBundle:Default:getMessageConversation2 }

wizardalley_chat_conversation_add_message:
    path:     /user/chat/addMessage
    defaults: { _controller: WizardalleyChatBundle:Default:addMessageConversation }