
page_gestion_show:
    path:     /page/gestion/show/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:GestionPage:index" }


page_gestion_edit:
    path:     /page/gestion/edit/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:GestionPage:editPage" }


page_gestion_user:
    path:     /page/gestion/user/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:GestionPage:editUserForm" }


page_gestion_user_edit:
    path:     /page/gestion/user/edit/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:GestionPage:editUser" }


page_gestion_publication:
    path:     /page/gestion/publication/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:GestionPage:displayPublicationUser" }

