
wizardalley_page_category:
    path:     /category/{category_id}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:categoryPageIndex" }

page_show:
    path:     /page/show/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:indexPage"}

page_like:
    path:     /user/page/like
    defaults: { _controller: "WizardalleyPublicationBundle:Page:likePage" }
    options:
        expose: true

page_publication_get:
    path:     /page/publication/get/{id}/{page}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:displayPublicationPage", page: 1 }
    options:
        expose: true

page_user_created_get:
    path:     /user/page/created/{page}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:getPageCreated", page: 1 }
    options:
        expose: true

page_user_editor_get:
    path:     /user/page/editor/{page}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:getPageEditor", page: 1 }
    options:
        expose: true

page_user_followed_get:
    path:     /user/page/followed/{page}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:getPageFollowed", page: 1 }
    options:
        expose: true