
page_show:
    path:     /page/show/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:indexPage" }



page_publication_get:
    path:     /page/publication/get/{id}/{page}
    defaults: { _controller: "WizardalleyPublicationBundle:Page:displayPublicationPage", page: 1 }