
comment_add:
    path:     /user/comment/add/{id}
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:addComment" }

comment_get:
    path:     /comment/get/{id}/{page}
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:getComment", page: 1 }

publication_get:
    path:     /publication/get/{id}/{page}
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:getPublication", page: 1 }

publication_show:
    path:     /publication/{id}/show
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:show" }

publication_new:
    path:     /user/publication/new/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:new" }

publication_create:
    path:     /user/publication/create/{id_page}
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:create" }
    methods:  POST

publication_edit:
    path:     /user/publication/{id}/edit
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:edit" }

publication_update:
    path:     /user/publication/{id}/update
    defaults: { _controller: "WizardalleyPublicationBundle:Publication:update" }
    methods:  [POST, PUT]

