<?php

namespace Wizardalley\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserConnectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WizardUserRepository extends EntityRepository
{

    public function findFriends($user){


        $sql = "
        select distinct w.username, w.id,w.path_profile
            from friends f1
                left join friends f2 on f2.user_id = f1.friend_user_id 
                left join wizard_user w on w.id = f2.user_id
            where
                f2.friend_user_id = ? and
                f1.user_id = ?
                ";
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare($sql);
        $result = $stmt->execute(array($user->getId(),$user->getId()));
        return $stmt->fetchAll();
    }
}
