<?php

namespace Wizardalley\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformationBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
    const LIMIT_ELEMENT = 1;

    /**
     * @param null $lastId
     *
     * @return array
     */
    public function findMore($lastId = null)
    {
        $qb = $this->_em->createQueryBuilder()
                        ->select('item')
                        ->from(
                            $this->_entityName,
                            'item'
                        )
        ;
        if ($lastId) {
            $qb->where('item.id < :last_id')
               ->setParameter(
                   'last_id',
                   $lastId
               )
            ;
        }
        $qb->orderBy(
            'item.id',
            'DESC'
        )
           ->setMaxResults(self::LIMIT_ELEMENT)
        ;

        return $qb->getQuery()
                  ->getScalarResult()
            ;
    }
}
