<?php

namespace Wizardalley\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Wizardalley\UserBundle\Controller\DefaultController;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentPublicationRepository extends EntityRepository
{
    /**
     * @param     $id_publication
     * @param int $page
     * @param int $limit
     *
     * @return array
     */
    public function findCommentsPublication($id_publication, $page = 1, $limit = DefaultController::BASE_LIMIT)
    {
        $firstResult = ($page - 1) * $limit;

        $qb     = $this->_em->createQueryBuilder()
                            ->select('c')
                            ->from(
                                $this->_entityName,
                                'c'
                            )
        ;
        $query  = $qb
            ->join(
                'c.publication',
                'p'
            )
            ->join(
                'c.user',
                'u'
            )
            ->addSelect('u.pathProfile')
            ->addSelect('u.username')
            ->addSelect('u.id')
            ->where('p.id = :id')
            ->orderBy(
                'c.dateComment',
                'DESC'
            )
            ->setFirstResult($firstResult)
            ->setMaxResults($limit)
            ->setParameter(
                ':id',
                $id_publication
            )
            ->getQuery()
        ;
        $result = $query->getArrayResult();

        return $result;
    }
}
