<?php

namespace Wizardalley\CoreBundle\Entity;

/**
 * InformationBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationBilletRepository extends AdminRepository
{
    /**
     * @param int $page
     * @param int $number
     * @return array
     */
    public function findInformationLimit($page, $number = 1)
    {
        $firstResult = ($page - 1) * $number;
        $qb = $this->_em->createQueryBuilder()
            ->select('i')
            ->from($this->_entityName, 'i');
        $query = $qb
            ->orderBy('i.datePublicationBillet','DESC')
            ->setFirstResult($firstResult)
            ->setMaxResults($number)
            ->getQuery();

        return $query->getResult();
    }
}
