<?php

namespace Wizardalley\CoreBundle\Entity;

/**
 * PageFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageFavoriteRepository extends AdminRepository
{
    /**
     * @param int $page
     * @param int $limit
     *
     * @return array
     */
    public function findPageLimit(
        $page = 1,
        $limit = 4
    ) {
        $firstResult = ($page - 1) * $limit;

        $qb = $this->_em->createQueryBuilder()->select('p')->from($this->_entityName, 'p');
        $query = $qb
            ->join('p.page', 'pa')
            ->addSelect('pa')
            ->orderBy('p.dateFavorite', 'DESC')
            ->setFirstResult($firstResult)
            ->setMaxResults($limit)
            ->getQuery();
        $result = $query->getArrayResult();

        return $result;
    }
}
