<?php

namespace Wizardalley\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Wizardalley\DefaultBundle\Controller\BaseController;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    /**
     * @param int $id_user
     * @param int $page
     * @param int $limit
     *
     * @return array
     */
    public function findPublications(
        $id_user,
        $page = 1,
        $limit = BaseController::BASE_LIMIT
    ) {
        $firstResult = ($page - 1) * $limit;

        $qb = $this->_em->createQueryBuilder()->select('p')->from($this->_entityName, 'p');
        $query = $qb
                    ->join('p.user', 'u')
                    ->where('u.id = :id and p.online = 1')
                    ->orderBy('p.created_at', 'DESC')
                    ->setFirstResult($firstResult)
                    ->setMaxResults($limit)
                    ->setParameter(':id', $id_user)
                    ->getQuery();
        $result = $query->getArrayResult();

        return $result;
    }

    /**
     * @param int $page
     * @param int $limit
     *
     * @return array
     */
    public function findMostCommentedPublications(
        $page = 1,
        $limit = BaseController::BASE_LIMIT
    ) {
        $firstResult = ($page - 1) * $limit;

        $qb = $this->_em->createQueryBuilder()->select('p')->from($this->_entityName, 'p');
        $query = $qb
                    ->join('p.user', 'u')
                    ->leftJoin('p.comments', 'c')
                    ->orderBy('count(c.id)', 'DESC')
                    ->orderBy('c.dateComment', 'DESC')
                    ->where('p.online = 1')
                    ->groupBy('p.id')
                    ->setFirstResult($firstResult)
                    ->setMaxResults($limit)
                    ->getQuery();
        $result = $query->getResult();

        return $result;
    }

    /**
     * @param string $like
     * @param int    $page
     * @param int    $limit
     *
     * @return array
     */
    public function findPublicationLike(
        $like,
        $page = 1,
        $limit = BaseController::BASE_LIMIT
    ) {
        $firstResult = ($page - 1)*$limit;
        
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p');
        $query = $qb
                    ->addSelect('i')
                    ->join('p.images', 'i')
                    ->where('p.title LIKE :like and p.online=1')
                    ->orderBy('p.title', 'DESC')
                    ->setFirstResult($firstResult)
                    ->setMaxResults($limit)
                    ->setParameter(':like', '%'.$like.'%')
                    ->getQuery();
        
        $result = $query->getArrayResult();

        return $result;
    }

    /**
     * @param int $id_page
     * @param int $page
     * @param int $limit
     *
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function findPublicationsPage(
        $id_page,
        $page = 1,
        $limit = BaseController::BASE_LIMIT
    ) {
        $firstResult = ($page - 1)*$limit;
        $sql = "
        select
            distinct w.username,
            w.path_profile as 'path_profile',
            w.id as 'user_id',
            pu.id as id,
            pu.title,
            pu.small_content,
            pa.content,
            pa.created_at,
            p.name as 'name',
            (
                SELECT
                    path
                FROM
                    image_publication ip
                WHERE
                    ip.publication_id = pu.id
                limit 1
            ) as path
            from
                abstract_publication pa
                left join publication pu
                    on pa.id = pu.id
                left join wizard_user w on w.id = pa.user_id 
                left join page p on p.id = pu.page_id
            where
                p.id = ? and pa.online = 1
                order by pa.created_at desc
                limit {$firstResult},{$limit}
                ";
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare($sql);
        $stmt->execute(array($id_page));

        return $stmt->fetchAll();
    }

    /**
     * @return array
     */
    public function findPublicationThisMonth()
    {
        $qb     = $this->_em->createQueryBuilder()->select('p')->from($this->_entityName, 'p');
        $query  = $qb->where('p.createdAt > :date and p.online = 1')
                     ->setParameter(':date', (new \DateTime())->format('Y-m'))
                     ->getQuery()
        ;
        $result = $query->getArrayResult();

        return $result;
    }

    /**
     * @param int $page
     * @param int $limit
     *
     * @return array
     */
    public function findPublicationFavorite($page, $limit = BaseController::BASE_LIMIT)
    {
        $firstResult = ($page - 1)*$limit;
        $qb = $this->_em->createQueryBuilder()->select('p')->from($this->_entityName, 'p');
        $query = $qb
                    ->join('p.favorite', 'f')
                    ->where('p.online = 1')
                    ->orderBy('f.dateFavorite', 'DESC')
                    ->setFirstResult($firstResult)
                    ->setMaxResults($limit)
                    ->getQuery();

        $result = $query->getResult();

        return $result;
    }



    /**
     * @return array
     */
    public function findLatestPublication()
    {
        $qb = $this->_em->createQueryBuilder()->select('p')->from($this->_entityName, 'p');
        $query = $qb
            ->orderBy('p.createdAt', 'DESC')
            ->where('p.online = 1')
            ->setMaxResults(2)
            ->getQuery();

        $result = $query->getResult();

        return $result;
    }
}
