<?php

namespace Wizardalley\CoreBundle\Entity;

/**
 * PublicationFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationFavoriteRepository extends AdminRepository
{
}
