<?php

namespace Wizardalley\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChatUserConnectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatUserConnectedRepository extends EntityRepository
{
     public function findUserConnected($id_current_user){
        $sql = "
            select distinct uc.chat_conversation_id, ucd.*, w.username
            from
              chat_user_connected ucd
            left join
              chat_user_conversation uc
                on ucd.id_id = uc.wizard_user_id
            left join 
              chat_conversation c 
                on c.id = uc.chat_conversation_id
            left join
              wizard_user w
                on w.id = uc.wizard_user_id
            where 
                w.id != ?
            ";
        
        $sql = "
            select u.*, w.username, cu.chat_conversation_id
            from 
            chat_user_connected u
              left join wizard_user w
                on w.id = u.id_id
              left join chat_user_conversation cu
                on cu.wizard_user_id = w.id
            where
                w.id != ?
                ";
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare($sql);
        $result = $stmt->execute(array($id_current_user));
        
         return $stmt->fetchAll();
    }
}
