<?php

namespace Wizardalley\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserConnectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository
{
    public function findConversationBetweenUser($id_user1,$id_user2){
        $sql = "
            select m.*, w.username
            from
            user_conversation uc1,
            user_conversation uc2
            join
            conversation c
            on uc2.conversation_id = c.id
            join chat_message m 
            on m.conversation_id = c.id
            join wizard_user w
            on w.id = m.user_id
            WHERE
            uc1.wizard_user_id = ? and
            uc2.wizard_user_id = ? and
            uc1.conversation_id = uc2.conversation_id AND
            c.multiple = 0
            ";
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare($sql);
        $result = $stmt->execute(array($id_user1,$id_user2));
        
         return $stmt->fetchAll();
    }
    
    public function getConversationBetweenMultipleUser($id_conversation){
        $sql = "
            select m.*, w.username
            from
            conversation c
            join chat_message m 
            on m.conversation_id = c.id
            join wizard_user w
            on w.id = m.user_id
            WHERE
            c.id = ? and
            c.multiple = 1
            ";
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare($sql);
        $result = $stmt->execute(array($id_conversation));
        
         return $stmt->fetchAll();
        
    }
}
