<?php

namespace Wizardalley\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserConnectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserConnectedRepository extends EntityRepository
{
     public function findUserConnected($id_current_user){
        $sql = "
            select distinct uc.conversation_id, ucd.*, w.username
            from
              user_connected ucd
            left join
              user_conversation uc
                on ucd.id_id = uc.wizard_user_id
            left join 
              conversation c 
                on c.id = uc.conversation_id
            left join
              wizard_user w
                on w.id = uc.wizard_user_id
            where 
                w.id != ? and
                c.multiple = 0
            ";
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare($sql);
        $result = $stmt->execute(array($id_current_user));
        
         return $stmt->fetchAll();
    }
}
