
wizardalley_search_display:
    path:     /search
    defaults: { _controller: WizardalleyDefaultBundle:Search:searchDisplay }
    

wizardalley_search_user:
    path:     /searchUser/{field}/{page}
    defaults: { _controller: WizardalleyDefaultBundle:Search:searchUser, page: 1 }
    options:
        expose: true

wizardalley_search_page:
    path:     /searchPage/{field}/{page}
    defaults: { _controller: WizardalleyDefaultBundle:Search:searchPage, page: 1 }
    options:
        expose: true

wizardalley_search_publication:
    path:     /searchPublication/{field}/{page}
    defaults: { _controller: WizardalleyDefaultBundle:Search:searchPublication, page: 1 }    
    options:
        expose: true
    

wizardalley_default_homepage:
    path:     /user/home
    defaults: { _controller: WizardalleyDefaultBundle:Default:index }

wizardalley_default_copyright:
    path:     /copyright
    defaults: { _controller: WizardalleyDefaultBundle:Default:copyright }

wizardalley_default_confidentiality:
    path:     /confidentiality
    defaults: { _controller: WizardalleyDefaultBundle:Default:confidentiality }

wizardalley_default_mention:
    path:     /mention
    defaults: { _controller: WizardalleyDefaultBundle:Default:mention }

wizardalley_default_contact:
    path:     /contact
    defaults: { _controller: WizardalleyDefaultBundle:Default:contactForm }
