

wizardalley_search:
    resource: "@WizardalleyDefaultBundle/Controller/SearchController.php"
    type:     annotation
    prefix:   /
wizardalley_discover:
    resource: "@WizardalleyDefaultBundle/Controller/DiscoverController.php"
    type:     annotation
    prefix:   /

wizardalley_information:
    resource: "@WizardalleyDefaultBundle/Controller/InformationController.php"
    type:     annotation
    prefix:   /

wizardalley_default:
    resource: "@WizardalleyDefaultBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
