<?php

namespace Wizardalley\PublicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentSmallPublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentSmallPublicationRepository extends EntityRepository
{
}
