<?php

namespace Wizardalley\PublicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImagePublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagePublicationRepository extends EntityRepository
{
}
