<?php

namespace Wizardalley\PublicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findLatestFollower($id_page, $limit= 9){
        $qb = $this->_em->createQueryBuilder()
            ->select('u')
            ->from("WizardalleyUserBundle:WizardUser", 'u');
        $query = $qb
                    ->join('u.pagesFollowed', 'p')
                    ->where('p.page = :id')
                    ->orderBy('p.dateInscription', 'desc')
                    ->setMaxResults($limit)
                    ->setParameter(':id', $id_page)
                    ->getQuery();
        $result = $query->getArrayResult();
        return $result;
    }
    
    public function findPage($id_page){
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from("WizardalleyPublicationBundle:Page", 'p');
        $query = $qb
                    ->where('p.id = :id')
                    ->setParameter(':id', $id_page)
                    ->getQuery();
        $result = $query->getArrayResult();
        return $result;
        
    }
}
