<?php

namespace Wizardalley\PublicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function findPublications( $id_user, $page = 1, $limit = 4){
        $firstResult = ($page - 1)*$limit;
        
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p');
        $query = $qb
                    ->join('p.user', 'u')
                    ->where('u.id = :id')
                    ->orderBy('p.datePublication','DESC')
                    ->setFirstResult($firstResult)
                    ->setMaxResults($limit)
                    ->setParameter(':id', $id_user)
                    ->getQuery();
        $result = $query->getArrayResult();
        return $result;
      
    }
    
    public function findPublicationLike($like, $page=1, $limit =4){
        $firstResult = ($page - 1)*$limit;
        
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p');
        $query = $qb
                    ->addSelect('i')
                    ->join('p.images', 'i')
                    ->where('p.title LIKE :like')
                    ->orderBy('p.title','DESC')
                    ->setFirstResult($firstResult)
                    ->setMaxResults($limit)
                    ->setParameter(':like', '%'.$like.'%')
                    ->getQuery();
        
        $result = $query->getArrayResult();
        return $result;
    }
    
    public function findPublicationsPage( $id_page, $page = 1, $limit = 4){
        

        $firstResult = ($page - 1)*$limit;
        $sql = "
        select distinct w.username, w.id as 'user_id',pu.id as id, pu.title, pu.small_content, pa.datePublication,
            (
                SELECT
                    path
                FROM
                    image_publication ip
                WHERE
                    ip.publication_id = pu.id
                limit 1
            ) as path
            from
                abstract_publication pa
                left join publication pu
                    on pa.id = pu.id
                left join wizard_user w on w.id = pa.user_id 
                left join page p on p.id = pu.page_id
            where
                p.id = ? 
                order by pa.datePublication desc
                limit {$firstResult},{$limit}
                ";
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare($sql);
        $result = $stmt->execute(array($id_page));
        return $stmt->fetchAll();
        
        
    }
}
