<?php

namespace Wizardalley\PublicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
        public function findPublications( $id_user, $page = 1, $limit = 4){
        $firstResult = ($page - 1)*$limit;
        
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p');
        $query = $qb
                    ->join('p.user', 'u')
                    ->where('u.id = :id')
                    ->orderBy('p.datePublication','DESC')
                    ->setFirstResult($firstResult)
                    ->setMaxResults($limit)
                    ->setParameter(':id', $id_user)
                    ->getQuery();
        $result = $query->getArrayResult();
        return $result;
      
    }
}
